version: "3"
services:
  navidrome:
    image: deluan/navidrome:latest
    user: "{{ navidrome_user }}:{{ navidrome_user }}" # should be owner of volumes
    ports:
      - "4533:4533"
    restart: unless-stopped
    environment:
      # Optional: put your config options customization here. Examples:
      ND_SCANSCHEDULE: 1h
      ND_LOGLEVEL: info  
      ND_SESSIONTIMEOUT: 24h
      ND_BASEURL: ""
    volumes:
      - "{{ navidrome_dir }}:/data"
      - "{{ music_dir }}:/music:ro"

  slskd:
    image: slskd/slskd
    container_name: slskd
    ports:
      - "5030:5030"
      - "5031:5031"
      - "50300:50300"
    environment:
      - SLSKD_REMOTE_CONFIGURATION=true
    volumes:
      - "{{ soulseek_dir }}:/app"
      - "{{ music_dir }}:/music:ro"
      - "{{ ebook_dir }}:/ebooks:ro"
    restart: unless-stopped