---
# Docker compose setup steps

- name: Copy compose source templates
  template:
    src: files/docker-compose.yml
    dest: "{{ docker_compose_dir }}/"
    mode: 0600

- name: Copy home assistant reverse proxy conf
  become: yes
  template:
    src: files/homeassistant.subdomain.conf
    dest: "{{ swag_proxy_dir }}/nginx/proxy-confs/"
    mode: 0600

- name: Copy reverse proxy cloudflare dns config
  become: yes
  template:
    src: files/cloudflare.ini
    dest: "{{ swag_proxy_dir }}/dns-conf/"
    mode: 0600

- name: Tear down existing services
  community.docker.docker_compose:
    project_src: "{{ docker_compose_dir }}"
    state: absent

- name: Create and start services
  community.docker.docker_compose:
    project_src: "{{ docker_compose_dir }}"
  register: output

- ansible.builtin.debug:
    var: output

- name: Run `docker-compose up` again
  community.docker.docker_compose:
    project_src: "{{ docker_compose_dir }}"
    build: no
  register: output

- ansible.builtin.debug:
    var: output

- ansible.builtin.assert:
    that: "not output.changed "

