- import_playbook: docker-server.yml

- hosts: home_assistant
  pre_tasks:
    - name: Setup dirs, users etc
      become: yes
      import_tasks: roles/home-assistant/tasks/pre-deploy.yml

  roles:
    - home-assistant
    - unifi-controller

  post_tasks:
    - name: Setup mqtt password
      become: yes
      import_tasks: roles/home-assistant/tasks/post-deploy.yml
