- import_playbook: docker-server.yml

- hosts: home_assistant
  tasks:
    - name: Include the HA role
      include_role:
        name: home-assistant

    - name: Include the Unifi controller role
      include_role:
        name: unifi-controller
