

- hosts: all
  become: true

  tasks:
          - name: Install aptitude using apt
            apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

          - name: Install system packages
            apt: name={{ item }} state=latest update_cache=yes
            loop: ['ca-certificates', 'curl', 'gnupg', 'lsb-release', 'python3-pip', 'virtualenv']

          - name: Add Docker GPG key
            apt_key:
                    url: https://download.docker.com/linux/ubuntu/gpg
                    state: present
            become: true

          - name: Add Docker to apt
            shell: echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

          - name: Install Docker
            apt: update_cache=yes name={{ item }} state=latest
            loop: ['docker-ce', 'docker-ce-cli', 'containerd.io']

          - name: Install Python Docker module
            pip:
                    name: docker

          - name: Install Python docker-compose module
            pip:
                    name: docker-compose

          - name: Add Docker group
            ansible.builtin.group:
                    name: docker
                    state: present

          - name: Add the user 'sypro' and append group 'docker'
            ansible.builtin.user:
                    name: sypro
                    groups: docker
                    append: yes
