influx_dir: "{{ ansible_env.HOME }}/.influxdb"
smokeping_dir: "{{ ansible_env.HOME }}/.smokeping"

docker_compose_dir: "{{ ansible_env.HOME }}/analytics-docker"

influx_mode: "setup"
influx_init_super_username: "{{ influx_init_super_username }}"
influx_init_super_password: "{{ influx_init_super_password }}"
influx_org: "home"
influx_bucket: "bucket"
influx_init_admin_token: "{{ influx_init_admin_token }}"

## Iotawatt power monitor
influx_ingestion_iotawatt_username: "{{ influx_ingestion_iotawatt_username }}"
influx_ingestion_iotawatt_password: "{{ influx_ingestion_iotawatt_password }}"
